application: cssbloggers
version: 1
runtime: python27
api_version: 1
threadsafe: yes
libraries:
- name: ssl
  version: latest

handlers:
- url: /js/*
  static_dir: static_root/js

- url: /img/*
  static_dir: static_root/img

- url: /css/*
  static_dir: static_root/css

# WARNING: Make sure this is login: admin.
# This url will be called by GAE periodically
# to update the feed.
- url: /pull_posts
  script: main.app
  login: admin # !IMPORTANT

# WARNING: Make sure this is login: admin.
# This url will be called by GAE periodically
# to update the feed.
- url: /tweet_posts
  script: main.app
  login: admin # !IMPORTANT

# Catch-all.
- url: .*
  script: main.app
